//
//  Models.swift
//  ExpandMind
//
//  Created by sanghyo on 2022/05/01.
//

import SwiftUI

struct Record : Hashable{
    let id: String
    let division: String
    let date: String
    let title: String
    let summary: String
    let thoughts: String
    var isBookmarked: Bool
}

struct Categories{
    let division: String
    var isSelected: Bool
}

func makeMockData() -> [Record] {
    [
        Record(id: "1i9kcBHX2Nw", division: "news", date: "2022. 03. 13", title: "스티브잡스 연설", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "ksZpu1s1LV0", division: "news", date: "2022. 03. 13", title: "페이스북 창업에 대해", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: false),
        Record(id: "KLe7Rxkrj94", division: "news", date: "2022. 03. 13", title: "더 락 당신은 누구인가? 당신의 그 에너지는 어디에서 흘러나오는가?", summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", thoughts: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isBookmarked: false),
        Record(id: "1BxY5PVUOek", division: "news", date: "2022. 03. 13", title: "우울감을 없애는 방법", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "1i9kcBHX2Nw", division: "news", date: "2022. 03. 13", title: "스티브잡스 연설", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "ksZpu1s1LV0", division: "news", date: "2022. 03. 13", title: "페이스북 창업에 대해", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: false),
        Record(id: "KLe7Rxkrj94", division: "news", date: "2022. 03. 13", title: "더 락 당신은 누구인가? 당신의 그 에너지는 어디에서 흘러나오는가?", summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", thoughts: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isBookmarked: false),
        Record(id: "1BxY5PVUOek", division: "news", date: "2022. 03. 13", title: "우울감을 없애는 방법", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "1i9kcBHX2Nw", division: "news", date: "2022. 03. 13", title: "스티브잡스 연설", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "ksZpu1s1LV0", division: "news", date: "2022. 03. 13", title: "페이스북 창업에 대해", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: false),
        Record(id: "KLe7Rxkrj94", division: "news", date: "2022. 03. 13", title: "더 락 당신은 누구인가? 당신의 그 에너지는 어디에서 흘러나오는가?", summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", thoughts: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isBookmarked: false),
        Record(id: "1BxY5PVUOek", division: "news", date: "2022. 03. 13", title: "우울감을 없애는 방법", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "1i9kcBHX2Nw", division: "news", date: "2022. 03. 13", title: "스티브잡스 연설", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "ksZpu1s1LV0", division: "news", date: "2022. 03. 13", title: "페이스북 창업에 대해", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: false),
        Record(id: "KLe7Rxkrj94", division: "news", date: "2022. 03. 13", title: "더 락 당신은 누구인가? 당신의 그 에너지는 어디에서 흘러나오는가?", summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", thoughts: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isBookmarked: false),
        Record(id: "1BxY5PVUOek", division: "news", date: "2022. 03. 13", title: "우울감을 없애는 방법", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "1i9kcBHX2Nw", division: "news", date: "2022. 03. 13", title: "스티브잡스 연설", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true),
        Record(id: "ksZpu1s1LV0", division: "news", date: "2022. 03. 13", title: "페이스북 창업에 대해", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: false),
        Record(id: "KLe7Rxkrj94", division: "news", date: "2022. 03. 13", title: "더 락 당신은 누구인가? 당신의 그 에너지는 어디에서 흘러나오는가?", summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", thoughts: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isBookmarked: false),
        Record(id: "1BxY5PVUOek", division: "news", date: "2022. 03. 13", title: "우울감을 없애는 방법", summary: "내용 요약", thoughts: "내 생각 적기", isBookmarked: true)

    ]
}
